import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-agreement-doc',
  templateUrl: './agreement-doc.component.html',
  styleUrl: './agreement-doc.component.scss'
})
export class AgreementDocComponent implements OnInit{

  agreementText: string | undefined;

  ngOnInit(): void {
    this.agreementText = "Sample Terms and Conditions Template\n" +
      "Terms and Conditions (\"Terms\")\n" +
      "Our Terms and Conditions were last updated on [DATE].\n" +
      "Please read these terms and conditions carefully before using Our Service.\n" +
      "Interpretation and Definitions\n" +
      "Interpretation\n" +
      "The words of which the initial letter is capitalized have meanings defined under the following conditions.\n" +
      "The following definitions shall have the same meaning regardless of whether they appear in singular or in\n" +
      "plural.\n" +
      "Definitions\n" +
      "For the purposes of these Terms and Conditions:\n" +
      "● “Affiliate” means an entity that controls, is controlled by or is under common control with a party,\n" +
      "where \"control\" means ownership of 50% or more of the shares, equity interest or other securities\n" +
      "entitled to vote for election of directors or other managing authority.\n" +
      "● “Account” means a unique account created for You to access our Service or parts of our Service.\n" +
      "● “Company” (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to\n" +
      "[COMPANY_INFORMATION].\n" +
      "● “Country” refers to [COMPANY_COUNTRY].\n" +
      "● “Content” refers to content such as text, images, or other information that can be posted, uploaded,\n" +
      "linked to or otherwise made available by You, regardless of the form of that content.\n" +
      "● “Device” means any device that can access the Service such as a computer, a cellphone or a digital\n" +
      "tablet.\n" +
      "● “Feedback” means feedback, innovations or suggestions sent by You regarding the attributes,\n" +
      "performance or features of our Service.\n" +
      "● “Products” refer to the products or items offered for sale on the Service.\n" +
      "● “Orders” mean a request by You to purchase Products from Us.\n" +
      "● “Promotions” refer to contests, sweepstakes or other promotions offered through the Service.\n" +
      "● “Service” refers to the Website.\n" +
      "● “Terms and Conditions” (also referred as \"Terms\") mean these Terms and Conditions that form the\n" +
      "entire agreement between You and the Company regarding the use of the Service. This Terms and\n" +
      "Conditions Agreement was generated by TermsFeed Terms and Conditions Generator.\n" +
      "● “Third-party Social Media Service” means any services or content (including data, information,\n" +
      "products or services) provided by a third-party that may be displayed, included or made available by\n" +
      "the Service.\n" +
      "● “Website” refers to [WEBSITE_NAME], accessible from [WEBSITE_URL]\n" +
      "● “You” means the individual accessing or using the Service, or the company, or other legal entity on\n" +
      "behalf of which such individual is accessing or using the Service, as applicable.\n" +
      "Acknowledgment\n" +
      "These are the Terms and Conditions governing the use of this Service and the agreement that operates\n" +
      "between You and the Company. These Terms and Conditions set out the rights and obligations of all users\n" +
      "regarding the use of the Service.\n" +
      "Your access to and use of the Service is conditioned on Your acceptance of and compliance with these\n" +
      "Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or\n" +
      "use the Service.\n" +
      "By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree\n" +
      "with any part of these Terms and Conditions then You may not access the Service.\n" +
      "You represent that you are over the age of 18. The Company does not permit those under 18 to use the\n" +
      "Service.\n" +
      "Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the\n" +
      "Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection,\n" +
      "use and disclosure of Your personal information when You use the Application or the Website and tells You\n" +
      "about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before\n" +
      "using Our Service.\n"
  }

}
